name: Update server-backend's submodule

on:
  workflow_run:
    workflows: ["Deploy to pages"]
    types:
      - completed

jobs:
  trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest commit title
        id: get_commit
        run: |
          echo "commit_title=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      - name: Trigger server-backend workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/BEComTweaks/server-backend/actions/workflows/106751072/dispatches \
            -d "{\"ref\":\"main\", \"inputs\":{\"title\":\"resource-packs: ${{ env.commit_title }}\"}}"
